// <auto-generated />
using System;
using Mango.Services.StrategyApi.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Mango.Services.StrategyAPI.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20231209100936_AddStrategysTo2")]
    partial class AddStrategysTo2
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Mango.Services.StrategyApi.Models.Strategy", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Categories")
                        .HasColumnType("nvarchar(max)");

                    b.Property<short?>("ComplexityLevel")
                        .HasColumnType("smallint");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsAIEnhanced")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RecommendedFor")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Resources")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Tags")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Strategies");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Categories = "[\"GoalSetting\",\"Personal Development\"]",
                            ComplexityLevel = (short)1,
                            CreatedAt = new DateTime(2023, 12, 9, 10, 9, 36, 345, DateTimeKind.Utc).AddTicks(6520),
                            Description = "Техника, помогающая формулировать цели так, чтобы они были конкретными, измеримыми, достижимыми, релевантными и ограниченными по времени.",
                            IsAIEnhanced = false,
                            Name = "SMART Goals",
                            RecommendedFor = "[\"Productivity\",\"Project Management\"]",
                            Resources = "[\"https://en.wikipedia.org/wiki/SMART_criteria\",\"https://www.mindtools.com/pages/article/smart-goals.htm\"]",
                            Tags = "[\"Career\",\"Personal Growth\"]",
                            UpdatedAt = new DateTime(2023, 12, 9, 10, 9, 36, 345, DateTimeKind.Utc).AddTicks(6520)
                        },
                        new
                        {
                            Id = 2,
                            Categories = "[\"GoalSetting\",\"Performance Management\"]",
                            ComplexityLevel = (short)3,
                            CreatedAt = new DateTime(2023, 12, 9, 10, 9, 36, 345, DateTimeKind.Utc).AddTicks(6570),
                            Description = "Система установления и отслеживания целей, использующая конкретные и ключевые результаты для измерения прогресса.",
                            IsAIEnhanced = false,
                            Name = "OKR - Objectives and Key Results",
                            RecommendedFor = "[\"Team Management\",\"Organizational Development\"]",
                            Resources = "[\"https://en.wikipedia.org/wiki/OKR\",\"https://www.whatmatters.com/faqs/okr-meaning-definition-example/\"]",
                            Tags = "[\"Business\",\"Teamwork\",\"Leadership\"]",
                            UpdatedAt = new DateTime(2023, 12, 9, 10, 9, 36, 345, DateTimeKind.Utc).AddTicks(6570)
                        },
                        new
                        {
                            Id = 3,
                            Categories = "[\"GoalSetting\",\"Motivation\"]",
                            ComplexityLevel = (short)2,
                            CreatedAt = new DateTime(2023, 12, 9, 10, 9, 36, 345, DateTimeKind.Utc).AddTicks(6600),
                            Description = "Техника визуализации целей, помогающая укрепить мотивацию и представление о конечных результатах.",
                            IsAIEnhanced = false,
                            Name = "Goal Visualization",
                            RecommendedFor = "[\"Personal Growth\",\"Motivation\"]",
                            Resources = "[\"https://positivepsychology.com/goal-visualization-techniques/\"]",
                            Tags = "[\"Self-improvement\",\"Motivation\"]",
                            UpdatedAt = new DateTime(2023, 12, 9, 10, 9, 36, 345, DateTimeKind.Utc).AddTicks(6600)
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
