// <auto-generated />
using System;
using Mango.Services.StrategyApi.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Mango.Services.StrategyAPI.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20231209102020_AddNoch4Strategys")]
    partial class AddNoch4Strategys
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Mango.Services.StrategyApi.Models.Strategy", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Categories")
                        .HasColumnType("nvarchar(max)");

                    b.Property<short?>("ComplexityLevel")
                        .HasColumnType("smallint");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsAIEnhanced")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RecommendedFor")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Resources")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Tags")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Strategies");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Categories = "[\"GoalSetting\",\"Personal Development\"]",
                            ComplexityLevel = (short)1,
                            CreatedAt = new DateTime(2023, 12, 9, 10, 20, 20, 149, DateTimeKind.Utc).AddTicks(8770),
                            Description = "Техника, помогающая формулировать цели так, чтобы они были конкретными, измеримыми, достижимыми, релевантными и ограниченными по времени.",
                            IsAIEnhanced = false,
                            Name = "SMART Goals",
                            RecommendedFor = "[\"Productivity\",\"Project Management\"]",
                            Resources = "[\"https://en.wikipedia.org/wiki/SMART_criteria\",\"https://www.mindtools.com/pages/article/smart-goals.htm\"]",
                            Tags = "[\"Career\",\"Personal Growth\"]",
                            UpdatedAt = new DateTime(2023, 12, 9, 10, 20, 20, 149, DateTimeKind.Utc).AddTicks(8770)
                        },
                        new
                        {
                            Id = 2,
                            Categories = "[\"GoalSetting\",\"Performance Management\"]",
                            ComplexityLevel = (short)3,
                            CreatedAt = new DateTime(2023, 12, 9, 10, 20, 20, 149, DateTimeKind.Utc).AddTicks(8830),
                            Description = "Система установления и отслеживания целей, использующая конкретные и ключевые результаты для измерения прогресса.",
                            IsAIEnhanced = false,
                            Name = "OKR - Objectives and Key Results",
                            RecommendedFor = "[\"Team Management\",\"Organizational Development\"]",
                            Resources = "[\"https://en.wikipedia.org/wiki/OKR\",\"https://www.whatmatters.com/faqs/okr-meaning-definition-example/\"]",
                            Tags = "[\"Business\",\"Teamwork\",\"Leadership\"]",
                            UpdatedAt = new DateTime(2023, 12, 9, 10, 20, 20, 149, DateTimeKind.Utc).AddTicks(8830)
                        },
                        new
                        {
                            Id = 3,
                            Categories = "[\"GoalSetting\",\"Motivation\"]",
                            ComplexityLevel = (short)2,
                            CreatedAt = new DateTime(2023, 12, 9, 10, 20, 20, 149, DateTimeKind.Utc).AddTicks(9010),
                            Description = "Техника визуализации целей, помогающая укрепить мотивацию и представление о конечных результатах.",
                            IsAIEnhanced = false,
                            Name = "Goal Visualization",
                            RecommendedFor = "[\"Personal Growth\",\"Motivation\"]",
                            Resources = "[\"https://positivepsychology.com/goal-visualization-techniques/\"]",
                            Tags = "[\"Self-improvement\",\"Motivation\"]",
                            UpdatedAt = new DateTime(2023, 12, 9, 10, 20, 20, 149, DateTimeKind.Utc).AddTicks(9010)
                        },
                        new
                        {
                            Id = 4,
                            Categories = "[\"TimeManagement\",\"Productivity\"]",
                            ComplexityLevel = (short)1,
                            CreatedAt = new DateTime(2023, 12, 9, 10, 20, 20, 149, DateTimeKind.Utc).AddTicks(9040),
                            Description = "Техника управления временем, разбивающая работу на короткие интервалы с короткими перерывами.",
                            IsAIEnhanced = false,
                            Name = "Pomodoro Technique",
                            RecommendedFor = "[\"Focus Improvement\",\"Task Management\"]",
                            Resources = "[\"https://francescocirillo.com/pages/pomodoro-technique\",\"https://en.wikipedia.org/wiki/Pomodoro_Technique\"]",
                            Tags = "[\"Efficiency\",\"Time Management\"]",
                            UpdatedAt = new DateTime(2023, 12, 9, 10, 20, 20, 149, DateTimeKind.Utc).AddTicks(9040)
                        },
                        new
                        {
                            Id = 5,
                            Categories = "[\"ProjectManagement\",\"Agile\"]",
                            ComplexityLevel = (short)2,
                            CreatedAt = new DateTime(2023, 12, 9, 10, 20, 20, 149, DateTimeKind.Utc).AddTicks(9060),
                            Description = "Гибкий метод управления задачами с использованием досок Канбан для визуализации рабочего процесса.",
                            IsAIEnhanced = false,
                            Name = "Kanban Method",
                            RecommendedFor = "[\"Workflow Management\",\"Team Collaboration\"]",
                            Resources = "[\"https://kanbanize.com/kanban-resources/getting-started/what-is-kanban\",\"https://en.wikipedia.org/wiki/Kanban\"]",
                            Tags = "[\"Agile\",\"Teamwork\",\"Productivity\"]",
                            UpdatedAt = new DateTime(2023, 12, 9, 10, 20, 20, 149, DateTimeKind.Utc).AddTicks(9060)
                        },
                        new
                        {
                            Id = 6,
                            Categories = "[\"Brainstorming\",\"Creativity\"]",
                            ComplexityLevel = (short)2,
                            CreatedAt = new DateTime(2023, 12, 9, 10, 20, 20, 149, DateTimeKind.Utc).AddTicks(9090),
                            Description = "Техника визуального мышления и планирования, использующая диаграммы для отображения взаимосвязей между различными идеями или задачами.",
                            IsAIEnhanced = false,
                            Name = "Mind Mapping",
                            RecommendedFor = "[\"Idea Generation\",\"Problem Solving\"]",
                            Resources = "[\"https://www.mindmapping.com/\",\"https://en.wikipedia.org/wiki/Mind_map\"]",
                            Tags = "[\"Creativity\",\"Planning\",\"Organization\"]",
                            UpdatedAt = new DateTime(2023, 12, 9, 10, 20, 20, 149, DateTimeKind.Utc).AddTicks(9090)
                        },
                        new
                        {
                            Id = 7,
                            Categories = "[\"TimeManagement\",\"DecisionMaking\"]",
                            ComplexityLevel = (short)1,
                            CreatedAt = new DateTime(2023, 12, 9, 10, 20, 20, 149, DateTimeKind.Utc).AddTicks(9110),
                            Description = "Метод управления задачами, основанный на разделении задач на категории по важности и срочности.",
                            IsAIEnhanced = false,
                            Name = "Eisenhower Box",
                            RecommendedFor = "[\"Prioritization\",\"Efficiency\"]",
                            Resources = "[\"https://www.eisenhower.me/eisenhower-matrix/\",\"https://en.wikipedia.org/wiki/Time_management#The_Eisenhower_Method\"]",
                            Tags = "[\"Productivity\",\"Focus\",\"Organization\"]",
                            UpdatedAt = new DateTime(2023, 12, 9, 10, 20, 20, 149, DateTimeKind.Utc).AddTicks(9110)
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
